<?php

namespace Database\Seeders;

use App\Models\Service;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $image_path = [
            'images/services/image1.png',
            'images/services/image2.png',
            'images/services/image3.png',
            'images/services/image4.png',
            'images/services/image5.png',
        ];
        $services = array(
            [
                'name' => 'オトモニ',
                "caption" => "定額で賢くクラフトビールを楽しもう冬から始める上質な楽しみのある暮らし",
                "area" => "関東",
                "price" => 3000,
                "service_cat_id" => 1,
                "service_content" => "Otomoni(オトモニ)は豊富な取り扱い銘柄から、
                    季節・お届けしたい体験・限定ビールの発売・お客様の好みなどに合わせて、
                    毎回丁寧に飲み比べセットをセレクトしてお届けするクラフトビールの定期便です。",
                "address" => "〒120-0015 東京都足立区足立",
                "rating" => 3,
                "image_url" => "images/services/image1.png",
                "zipcode" => "1200015",
            ],
            [
                'name' => 'always LUNCH',
                "caption" => "API は商用、非商用を問わず、無料でご利用になれます。",
                "area" => "関東",
                "price" => 7000,
                "service_cat_id" => 1,
                "service_content" => "Go To Eat ポイント利用対象店三宮にあるおすすめのお店",
                "address" => "〒120-0012 東京都足立区青井",
                "rating" => 4,
                "image_url" => "images/services/image2.png",
                "zipcode" => "1200012",
            ],
            [
                'name' => 'エースコンタクト',
                'service_cat_id' => 1,
                "caption" => "当店では各テーブル無煙ロースター設置により約３分",
                "area" => "関東",
                "price" => 2000,
                "service_content" => "各テーブルごとの無煙ロースターにより約３分で店内換気しています！
                神戸肉流通推進協議会加盟店・神戸牛一頭買いにて入荷
                大小個室有り！最大６０名様まで！",
                "address" => "〒121-0012 東京都足立区青井",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "1210012",
            ],
            [
                'name' => '「出品者」と「購入者」がチャットできる',
                'service_cat_id' => 1,
                "caption" => "当店では各テーブル無煙ロースター設置により約３分",
                "area" => "関東",
                "price" => 21200,
                "service_content" => "チャットする相手ごとに、「メッセージ未読数」「最終メッセージ送受信時刻」が表示される。",
                "address" => "〒121-0064 東京都足立区保木間",
                "rating" => 2,
                "image_url" => "images/services/image6.png",
                "zipcode" => "1210064",
            ],
            [
                'name' => '添付画像・ファイルがアップロードできる。',
                'service_cat_id' => 1,
                "caption" => "当店では各テーブル無煙ロースター設置により約３分",
                "area" => "関東",
                "price" => 20200,
                "service_content" => "LINEのように、プロフィールのアイコンが表示され、ふきだしのようなデザインになる。",
                "address" => "〒197-0827 東京都あきる野市油平",
                "rating" => 5,
                "image_url" => "images/services/image4.png",
                "zipcode" => "1970827",
            ],
            [
                'name' => 'MECHAKARI',
                'service_cat_id' => 1,
                "caption" => "当店では各テーブル無煙ロースター設置により約３分",
                "area" => "関東",
                "price" => 10000,
                "service_content" => "各テーブルごとの無煙ロースターにより約３分で店内換気しています！
                神戸肉流通推進協議会加盟店・神戸牛一頭買いにて入荷
                大小個室有り！最大６０名様まで！",
                "address" => "〒190-0155 東京都あきる野市網代",
                "rating" => 5,
                "image_url" => "images/service_courses/imgDefault.png",
                "zipcode" => "1900155",
            ],
            [
                'name' => 'GooPass',
                'service_cat_id' => 1,
                "caption" => "ＪＲ三宮駅徒歩３分",
                "area" => "関東",
                "price" => 1000,
                "service_content" => "神戸肉流通推進協議会加盟店、定期的に優秀賞受賞の神戸牛を一頭買いにて仕入れしています！",
                "address" => "〒197-0828 東京都あきる野市秋留",
                "rating" => 4,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "1970828",
            ],
            [
                'name' => 'KURANDO CLUB',
                'service_cat_id' => 1,
                "caption" => "ＪＲ三宮駅徒歩３1分",
                "area" => "関東",
                "price" => 3000,
                "service_content" => "極上の神戸牛と極上の黒毛和牛焼肉店として神戸三宮で愛され続ける『大長今』の本店です。",
                "address" => "〒197-0824 東京都あきる野市切欠",
                "rating" => 5,
                "image_url" => "images/service_courses/imgDefault.png",
                "zipcode" => "1970824",
            ],
            [
                'name' => 'Ehon Club',
                'service_cat_id' => 2,
                "caption" => "ＪＲ三宮駅徒歩21分",
                "area" => "関東",
                "price" => 22000,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒190-0162 東京都あきる野市三内",
                "rating" => 2,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "1900162",
            ],
            [
                'name' => 'Toysub!',
                'service_cat_id' => 2,
                "caption" => "ＪＲ三宮駅徒歩124分",
                "area" => "関西",
                "price" => 3000,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒574-0046 大阪府大東市赤井",
                "rating" => 3,
                "image_url" => "images/services/image6.png",
                "zipcode" => "5740046",
            ],
            [
                'name' => '寿司処 喜与丸 大丸京都店',
                'service_cat_id' => 2,
                "caption" => "ＪＲ三宮駅徒歩24431分",
                "area" => "関西",
                "price" => 11000,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒574-0076 大阪府大東市曙町",
                "rating" => 4,
                "image_url" => "images/services/image1.png",
                "zipcode" => "5740076",
            ],
            [
                'name' => '京都 豚しゃぶ英 四条烏丸本店',
                'service_cat_id' => 2,
                "caption" => "ＪTTTTＲ三宮駅徒歩2561分",
                "area" => "関西",
                "price" => 3600,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒574-0003 大阪府大東市明美の里町",
                "rating" => 4,
                "image_url" => "images/services/image3.png",
                "zipcode" => "5740003",
            ],
            [
                'name' => 'THE THOUSAND KYOTO',
                'service_cat_id' => 2,
                "caption" => "ＪAAＲ三宮駅徒歩21分",
                "area" => "関西",
                "price" => 3700,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒574-0061 大阪府大東市大東町",
                "rating" => 3,
                "image_url" => "images/services/image2.png",
                "zipcode" => "5740061",
            ],
            [
                'name' => 'Coffee Base KANONDO',
                'service_cat_id' => 2,
                "caption" => "ＪAAＲ三宮駅徒歩21分",
                "area" => "関西",
                "price" => 3100,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒574-0027 大阪府大東市三住町",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "5740027",
            ],
            [
                'name' => 'Len',
                'service_cat_id' => 3,
                "caption" => "選な目利きで選ぶＡ４、Ａ５等級の神",
                "area" => "東北",
                "price" => 4700,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒028-7635 岩手県八幡平市愛の山",
                "rating" => 4,
                "image_url" => "images/service_courses/imgDefault.png",
                "zipcode" => "0287635",
            ],
            [
                'name' => 'TEE REX',
                'service_cat_id' => 3,
                "caption" => "選な目利きで選ぶＡ9、Ａ５等級の神",
                "area" => "東北",
                "price" => 5500,
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒028-7619 岩手県八幡平市相沢",
                "rating" => 2,
                "image_url" => "images/services/image5.png",
                "zipcode" => "0287619",
            ],
            [
                'name' => 'subsclife',
                'service_cat_id' => 3,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5700,
                "area" => "東北",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒025-0067 岩手県花巻市浅沢",
                "rating" => 5,
                "image_url" => "images/services/image6.png",
                "zipcode" => "0250067",
            ],
            [
                'name' => 'CLAS',
                'service_cat_id' => 3,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5000,
                "area" => "東北",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒025-0071 岩手県花巻市愛宕町",
                "rating" => 4,
                "image_url" => "images/service_courses/imgDefault.png",
                "zipcode" => "0250071",
            ],
            [
                'name' => 'SANU',
                'service_cat_id' => 3,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 17800,
                "area" => "四国",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒761-2101 香川県綾川町畑田",
                "rating" => 3,
                "image_url" => "images/services/image1.png",
                "zipcode" => "7612101",
            ],
            [
                'name' => 'Laxus',
                'service_cat_id' => 3,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5000,
                "area" => "四国",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒761-2207 香川県綾川町羽床上",
                "rating" => 1,
                "image_url" => "images/service_courses/imgDefault.png",
                "zipcode" => "7612207",
            ],
            [
                'name' => 'bloomee',
                'service_cat_id' => 3,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 14000,
                "area" => "四国",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒761-2308 香川県綾川町羽床下",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "7612308",
            ],
            [
                'name' => 'Native Camp',
                'service_cat_id' => 3,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 52000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒623-0062 京都府綾部市相生町",
                "rating" => 5,
                "image_url" => "images/service_courses/imgDefault.png",
                "zipcode" => "6230062",
            ],
            [
                'name' => 'Craftie Home',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒623-0104 京都府綾部市安国寺町",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "6230104",
            ],
            [
                'name' => 'snaq me.',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒623-0011 京都府綾部市青野町",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "6230011",
            ],
            [
                'name' => 'チャット機能.',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 16000,
                "area" => "関西",
                "service_content" => "「出品者」と「購入者」がチャットできる。サイト運営側からチャット（メッセージ）できる。",
                "address" => "〒623-0006 京都府綾部市有岡町",
                "rating" => 4,
                "image_url" => "images/services/image5.png",
                "zipcode" => "6230006",
            ],
            [
                'name' => '決済機能',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6000,
                "area" => "九州",
                "service_content" => "クレジットカード決済を対応とする。",
                "address" => "〒874-0819 大分県別府市浜脇",
                "rating" => 4,
                "image_url" => "images/services/image1.png",
                "zipcode" => "8740819",
            ],
            [
                'name' => 'PostCoffee',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒874-0005 大分県別府市天間",
                "rating" => 5,
                "image_url" => "images/services/image1.png",
                "zipcode" => "8740005",
            ],
            [
                'name' => 'Hito Hana',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 23000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒874-0902 大分県別府市青山町",
                "rating" => 5,
                "image_url" => "images/services/image6.png",
                "zipcode" => "8740902",
            ],
            [
                'name' => 'BASE FOOD',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 11100,
                "area" => "東北",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒999-8431 山形県飽海郡遊佐町菅里十里塚",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "9998431",
            ],
            [
                'name' => 'cafe maison',
                'service_cat_id' => 4,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1613 佐賀県藤津郡太良町大浦丙",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491613",
            ],
            [
                'name' => 'subsc',
                'service_cat_id' => 5,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 53000,
                "area" => "四国",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒770-0815 徳島県徳島市助任橋",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "7700815",
            ],
            [
                'name' => 'BLOOM BOX',
                'service_cat_id' => 5,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 52000,
                "area" => "東北",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒999-8433 山形県飽海郡遊佐町",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "9998433",
            ],
            [
                'name' => 'MECHAKARI',
                'service_cat_id' => 5,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 75000,
                "area" => "東北",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒999-8437 山形県飽海郡遊佐町藤崎",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "9998437",
            ],
            [
                'name' => 'ビズ服',
                'service_cat_id' => 5,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 12000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒623-0062 京都府綾部市相生町",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6230062",
            ],
            [
                'name' => 'リネット',
                'service_cat_id' => 5,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒623-0064 京都府綾部市中ノ町",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6230064",
            ],
            [
                'name' => 'GooPass',
                'service_cat_id' => 5,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 2000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒623-0012 京都府綾部市川糸町",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "6230012",
            ],
            [
                'name' => 'ゼロcafe',
                'service_cat_id' => 5,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 12000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒623-0011 京都府綾部市青野町",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "6230011",
            ],
            [
                'name' => 'OFFICE PASS',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒625-0012 京都府舞鶴市白屋町",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "6250012",
            ],
            [
                'name' => 'HIDEOUT CLUB',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 9000,
                "area" => "東北",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒999-8437 山形県飽海郡遊佐町藤崎",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "9998437",
            ],
            [
                'name' => 'KURANDO CLUB',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 2300,
                "area" => "東北",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒999-8438 山形県飽海郡遊佐町比子",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "9998438",
            ],
            [
                'name' => 'THE STELLA',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 11000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8345 京都府八幡市橋本愛宕山",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6148345",
            ],
            [
                'name' => '絵本クラブ',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 23000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8346 京都府八幡市橋本塩釜",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6148346",
            ],
            [
                'name' => 'WorldLibrary Personal',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 2200,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "大阪府大阪市北区天神橋7-3-2大山ビル603号室",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'トイサブ！',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 4400,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8348 京都府八幡市橋本東原",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "6148348",
            ],
            [
                'name' => 'おトクにマイカー 定額カルモくん',
                'service_cat_id' => 6,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 4000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8344 京都府八幡市橋本堂ケ原",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6148344",
            ],
            [
                'name' => 'Doctors Me',
                'service_cat_id' => 7,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8321 京都府八幡市橋本米ノ尾",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "6148321",
            ],
            [
                'name' => 'SASAYA',
                'service_cat_id' => 7,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 50400,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8322 京都府八幡市橋本狩尾",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "6148322",
            ],
            [
                'name' => 'ADDress',
                'service_cat_id' => 7,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 22000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8325 京都府八幡市橋本北浄土ケ原",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "6148325",
            ],
            [
                'name' => 'Hostel life',
                'service_cat_id' => 7,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5200,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8326 京都府八幡市橋本石ケ谷",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "6148326",
            ],
            [
                'name' => 'Xross house',
                'service_cat_id' => 7,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8331 京都府八幡市橋本意足",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6148331",
            ],
            [
                'name' => 'HafH',
                'service_cat_id' => 7,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 7000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8333 京都府八幡市橋本東刈又",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6148333",
            ],
            [
                'name' => 'LUCUAフードパスポート',
                'service_cat_id' => 8,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 95000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒614-8334 京都府八幡市橋本西刈又",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6148334",
            ],
            [
                'name' => 'EMBANKMENT Coffee',
                'service_cat_id' => 8,
                "price" => 8500,
                "area" => "関西",
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒617-0811 京都府長岡京市粟生",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "6170811",
            ],
            [
                'name' => 'meeth',
                'service_cat_id' => 8,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 2200,
                "area" => "四国",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒617-0814 京都府長岡京市今里",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "6170814",
            ],
            [
                'name' => 'LUCIAフードパスポート',
                'service_cat_id' => 8,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 22000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒621-0815 京都府亀岡市古世町",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "6210815",
            ],
            [
                'name' => 'Tokyo Coffee',
                'service_cat_id' => 8,
                "price" => 8000,
                "area" => "四国",
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒770-0822 徳島県徳島市東出来島町",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "7700822",
            ],
            [
                'name' => 'Paris By Night',
                'service_cat_id' => 8,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 21200,
                "area" => "四国",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒770-0823 徳島県徳島市出来島本町",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "7700823",
            ],
            [
                'name' => '村橋庭ン',
                'service_cat_id' => 9,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 12000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1221 滋賀県愛知郡愛荘町下八木",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "5291221",
            ],
            [
                'name' => 'ホーム建築',
                'service_cat_id' => 9,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 15000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1223 滋賀県愛知郡愛荘町島川",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "5291223",
            ],
            [
                'name' => 'Bigbang建設',
                'service_cat_id' => 9,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 14000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1226 滋賀県愛知郡愛荘町南野々目",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "5291226",
            ],
            [
                'name' => 'Cherry家',
                'service_cat_id' => 9,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 22000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1223 滋賀県愛知郡愛荘町島川",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "5291223",
            ],
            [
                'name' => 'Vin不動産',
                'service_cat_id' => 9,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 40000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1225 滋賀県愛知郡愛荘町栗田",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "5291225",
            ],
            [
                'name' => 'PARA建物',
                'service_cat_id' => 9,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 30000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "大阪府大阪市北区芝田1-10-10 芝田グランドビル608号室",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Linhfashion',
                'service_cat_id' => 10,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1231 滋賀県愛知郡愛荘町円城寺",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "5291231",
            ],
            [
                'name' => 'Phuongおしゃれ',
                'service_cat_id' => 10,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 10000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1235 滋賀県愛知郡愛荘町目加田",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "5291235",
            ],
            [
                'name' => 'ThuyBoutique',
                'service_cat_id' => 10,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 28000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒529-1237 滋賀県愛知郡愛荘町西出",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "5291237",
            ],
            [
                'name' => 'もりストア',
                'service_cat_id' => 10,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒555-0000 大阪府大阪市西淀川区御幣島２",
                "rating" => 2,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "5550000",
            ],
            [
                'name' => 'TokyoDaily',
                'service_cat_id' => 10,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 32000,
                "area" => "関西",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒555-0001 大阪府大阪市西淀川区佃",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "5550001",
            ],
            [
                'name' => 'Daiso',
                'service_cat_id' => 10,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 10000,
                "area" => "中部",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒500-0000 岐阜県岐阜市",
                "rating" => 3,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "5000000",
            ],
            [
                'name' => 'Go家電',
                'service_cat_id' => 11,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 12000,
                "area" => "中国",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒700-0000 岡山県岡山市北区津島",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "7000000",
            ],
            [
                'name' => 'Coop生活用品店',
                'service_cat_id' => 11,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 14900,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒800-0000 福岡県北九州市門司区",
                "rating" => 4,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "8000000",
            ],
            [
                'name' => 'Aeon',
                'service_cat_id' => 11,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 18000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Alibaba',
                'service_cat_id' => 11,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 21000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Hemer',
                'service_cat_id' => 11,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 19400,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Kongo',
                'service_cat_id' => 11,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 10000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Kanguroo',
                'service_cat_id' => 12,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 28000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'BigC',
                'service_cat_id' => 12,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 18000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Hello',
                'service_cat_id' => 12,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 15000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'FAN',
                'service_cat_id' => 12,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 21000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Deathnote',
                'service_cat_id' => 12,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 1,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Lawliet',
                'service_cat_id' => 12,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 2000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 0,
                "image_url" => "images/services/image6.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Light',
                'service_cat_id' => 13,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 2000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 0,
                "image_url" => "images/services/image6.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Ruyk宿泊',
                'service_cat_id' => 13,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 4000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'おきた',
                'service_cat_id' => 13,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Danish',
                'service_cat_id' => 13,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 12000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '大和旅行',
                'service_cat_id' => 13,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 18000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 5,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Sunday旅行',
                'service_cat_id' => 13,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 14000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'SUN交通',
                'service_cat_id' => 14,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 12000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Iconic',
                'service_cat_id' => 14,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 14000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/imgDefault.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '富士通',
                'service_cat_id' => 14,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 20200,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ほたる',
                'service_cat_id' => 14,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 12200,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Uchiha',
                'service_cat_id' => 14,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '木の葉',
                'service_cat_id' => 14,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 0,
                "image_url" => "images/services/image6.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'まだら',
                'service_cat_id' => 15,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 4600,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ＭＡＧＩＣ',
                'service_cat_id' => 15,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ＡＬＭＯＮＤ',
                'service_cat_id' => 15,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 7000,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '第一',
                'service_cat_id' => 15,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6700,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'コンパック',
                'service_cat_id' => 15,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8400,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '２ＮＸ',
                'service_cat_id' => 15,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 7900,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 5,
                "image_url" => "images/services/image5.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '虎杖コスメ',
                'service_cat_id' => 16,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 7900,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ＹＵＵＭＩ',
                'service_cat_id' => 16,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "zipcode" => "8491614",
                "price" => 8600,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ＡＰＯＬＬＯ',
                'service_cat_id' => 16,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 7600,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Ｒ・Ｅ・Ｎ',
                'service_cat_id' => 16,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5600,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ＨＰ',
                'service_cat_id' => 16,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6700,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ＹＳＬ',
                'service_cat_id' => 16,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 9300,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ＪＵＮＩＯＲ',
                'service_cat_id' => 16,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 5200,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'まるこ',
                'service_cat_id' => 17,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8300,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'ドラえもん',
                'service_cat_id' => 17,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 8600,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '伊藤店',
                'service_cat_id' => 17,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6400,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Ｐｏｋｅｍｏｎ',
                'service_cat_id' => 17,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 6900,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 3,
                "image_url" => "images/services/image3.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => 'Ｏｎｅｏｋ',
                'service_cat_id' => 17,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 9200,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 4,
                "image_url" => "images/services/image4.png",
                "zipcode" => "8491614",
            ],
            [
                'name' => '1998',
                'service_cat_id' => 17,
                "caption" => "の神戸牛、但馬牛などの上質なお肉を",
                "price" => 4600,
                "area" => "九州",
                "service_content" => "厳選な目利きで選ぶＡ４、Ａ５等級の神戸牛、但馬牛などの上質なお肉を、会席コースなどな楽しみ方で提供させていただきます。",
                "address" => "〒849-1614 佐賀県藤津郡太良町竹崎甲",
                "rating" => 2,
                "image_url" => "images/services/image2.png",
                "zipcode" => "8491614",
            ]
        );

        foreach ($services as $key => $service) {
            $s = new Service();
            $s['id'] = $key + 1;
            $s['hash_id'] = md5($key + 1);
            $s['seller_id'] = random_int(1, 7);
            $s['service_type_id'] =  ($key + 1) <= 10 ? random_int(2, 3) : random_int(1, 5);
            $s['name'] = $service['name'];
            $s['area'] = $service['area'];
            $s['caption'] = $service['caption'];
            $s['service_content'] = $service['service_content'];
            $s['address'] = $service['address'];
            $s['max'] = random_int(1, 1000);
            $s['service_cat_id'] = $service['service_cat_id'];
            $s['is_reserves'] = ($key + 1) <= 10 ? 1 : 0;
            // $s['age_confirm'] = '20';
            $s['is_draft'] = false;
            $s['private'] = false;
            $s['enabled'] = true;
            if ($key < 10) {
                $s['sort_type'] = 1;
            } else if ($key > 10 && $key < 20) {
                $s['sort_type'] = 2;
            } else if ($key > 20 && $key < 30) {
                $s['sort_type'] = 3;
            }
            $s['created_at'] = Carbon::now()->addMinutes($key+1)->toDateTimeString();
            $s['updated_at'] = Carbon::now()->addMinutes($key+1)->toDateTimeString();
            $s->save();

            DB::table('service_courses')->insert([
                "service_id" => $key + 1,
                "course_id" => "A" . ($key + 1),
                "name" => "course " . ($key + 1),
                "price" => $service['price'],
                "cycle" => random_int(1,3),
                "content" => "・BASE BREAD プレーン、チョコレート、メープル、シナモン客２食（4袋）
                ・BASE Cookies ココア、アールグレイ、客１食（4袋）
                ＋BASE Cookies アールグレイ１袋無料プレゼント
                ＋BASE Cookies アールグレイ１袋無料プレゼント
                ＋BASE Cookies アールグレイ１袋無料プレゼント",
                // "max" => 100,
                "firstPr" => random_int(0,1)
            ]);

            DB::table('service_course_images')->insert([
                "course_id" => "A" . ($key + 1),
                "image_url" => $service['image_url'],
            ]);

            if($key+1 <= 10 ){
                DB::table('service_images')->insert([
                    "service_id" => $key + 1,
                    "image_url" => $service['image_url'],
                ]);
                for ($i = 0; $i < 4; $i++) {
                    DB::table('service_images')->insert([
                        "service_id" => $key + 1,
                        "image_url" => $image_path[random_int(0,4)],
                    ]);
                }
            }
            if( ($key+1) >= 10 && ($key+1) <= 15) {
                DB::table('service_reviews')->insert([
                    'id' => $key + 1,
                    "service_id" => $key + 1,
                    "rating" => $service['rating'],
                    "description" => "良い",
                    "buyer_id" => 2,
                    "seller_reply" => '売り手の返信'
                ]);
                for ($i = 0; $i < 4; $i++) {
                    DB::table('service_reviews_images')->insert([
                        "reviews_id" => $key + 1,
                        "image_url" => $image_path[random_int(0,4)],
                    ]);
                }
                DB::table('service_images')->insert([
                    "service_id" => $key + 1,
                    "image_url" => $service['image_url'],
                ]);
            } elseif(($key+1) >= 15) {
                DB::table('service_images')->insert([
                    "service_id" => $key + 1,
                    "image_url" => $service['image_url'],
                ]);
                DB::table('service_reviews')->insert([
                    'id' => $key + 1,
                    "service_id" => $key + 1,
                    "rating" => $service['rating'],
                    "description" => "良い",
                    "buyer_id" => 2,
                    "seller_reply" => '売り手の返信'
                ]);
            }
        }
    }
}
